#!/usr/bin/php -q
<?php
/*******************************************************************\
*            Gemeinschaft - asterisk cluster gemeinschaft
* 
* $Revision$
* 
* Copyright 2007, amooma GmbH, Bachstr. 126, 56566 Neuwied, Germany,
* http://www.amooma.de/
*
* Author: Sven Neukirchner <s.neukirchner@konabi.de>
* 
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* as published by the Free Software Foundation; either version 2
* of the License, or (at your option) any later version.
* 
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
* MA 02110-1301, USA.
\*******************************************************************/
 
define( 'GS_VALID', true );  /// this is a parent file

ini_set('implicit_flush', 1);
ob_implicit_flush(1);


$user = trim(@$argv[1]);
$review_start = trim(@$argv[2]); 
$call_id = trim(@$argv[3]); 
$queue_exten = trim(@$argv[4]); 


if (! preg_match('/^\d+$/', $user))  // is not just digits
	die();
if (! preg_match('/^\d+$/', $review_start))  // is not just digits
	die();	
if (! $call_id)
	die();		

require_once( dirName(__FILE__) .'/../inc/conf.php' );
include_once( GS_DIR .'inc/db_connect.php' );
$db = gs_db_master_connect();

# get user id
#
$user_id = (int)$db->executeGetOne( 'SELECT `_user_id` FROM `ast_sipfriends` WHERE `name`=\''. $db->escape($user) .'\'' );
if ($user_id < 1) die(); 

# get user's host id
#
$user_host_id = (int)$db->executeGetOne( 'SELECT `host_id` FROM `users` WHERE `id`='. $user_id );
if ($user_host_id < 1) die(); 

$new_agent_state = 3;
# set new agent state
#
$rs = $db->execute( 'UPDATE `agent_state` SET `state`='. $new_agent_state .',  `timestamp`='. $review_start .', `ast_call_id`='. $call_id .' WHERE `_user_id`='. $user_id );
if(! @$rs) gs_agi_err( 'Coult not set new agent status' );  	

?>